export { ContactUsPage } from './ContactUsPage'
export { NotFoundPage } from './NotFoundPage'
export { PrivacyPolicyPage } from './PrivacyPolicyPage'
export { RegisterPage } from './RegisterPage'
export { TermsAndConditionsPage } from './TermsAndConditionsPage'
