name: Build Application

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Install Node 20.4.0
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8
        with:
          node-version: 20.4.0

      - name: NPM clean install
        run: npm ci

      - name: Build the application
        run: npm run build --if-present

      - name: Test the application
        run: npm test
